### ISSUE TITLE
docs: instrução de instalação do projeto com link incorreto

### ISSUE THREAD

**Issue by RaphaelOliveiraMoura** [natahouse/timezones#3]
# ✏️ Descrição
No README do repositório na seção de `Instalação` as instruções estão com link de outro repositório. Sugestão seria utilizar o link desse repositório: `https://github.com/natahouse/timezones`

# 🖼️🔗 Screenshots ou Links
Segue abaixo o print da forma como está atualmente:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/41276009/194912952-5c0206ad-8ced-4086-897a-19749f42c4ca.png">

**Comment by saulojoab** [comment]
ops KKKKKKKK tava usando o template deles como base e botei o link dos cara
valeeeu
